export enum Tags
{
    BACKGROUND = "BACKGROUND",
    ENEMY_CIRCLE = "ENEMY_CIRCLE",
    PLAYER_PROJECTILE = "PLAYER_PROJECTILE",
    PLAYER = "PLAYER",
    PLAYER_1 = "PLAYER_1",
    PLAYER_2 = "PLAYER_2",
    STATUS_BAR = "STATUS_BAR"
}

export enum Messages
{
    BUTTON_CHANGE = "BUTTON_CHANGE",
    ENEMY_COLLISION = "ENEMY_COLLISION",
    ENEMY_DESTROYED = "ENEMY_DESTROYED",
    GAME_MODE_SELECTED = "GAME_MODE_SELECTED",
    GAME_OVER = "GAME_OVER",
    LEVEL_FINISHED = "LEVEL_FINISHED",
    LEVEL_START = "LEVEL_START",
    MAIN_MENU = "MAIN_MENU",
    PLAYER_DEAD = "PLAYER_DEAD",
    PLAYER_HIT = "PLAYER_HIT",
    PROJECTILE_DESTROYED = "PROJECTILE_DESTROYED",
    PROJECTILE_COLLISION = "PROJECTILE_COLLISION",
    PROJECTILE_SHOT = "PROJECTILE_SHOT"
}

export enum Attributes
{
    CONTROLS = "CONTROLS",
    ENEMY_SPEED = "ENEMY_SPEED",
    ENEMY_TYPE = "ENEMY_TYPE",
    ENEMY_VELOCITY = "ENEMY_VELOCITY",
    PLAYER_LAST_COLLISION = "PLAYER_LAST_COLLISION",  // absolute time of last collision of player
    PLAYER_LIVES = "PLAYER_LIVES",
    PLAYER_NUMBER = "PLAYER_NUMBER",
    PROJECTILES_AVAILABLE = "PROJECTILES_AVAILABLE",
    PROJECTILE_SHOOTER = "PROJECTILE_SHOOTER"  // the person that shot the projectile
}

export enum GlobalAttributes
{
    GAME_STATE = "GAME_STATE",
}

export enum GameAssets
{
    BACKGROUND = "BACKGROUND",
    LEVELS = "LEVELS",
    SPRITE_HEART = "SPRITE_HEART",
    SPRITESHEET_ENEMIES = "SPRITESHEET_ENEMIES",
    SPRITESHEET_PLAYER_1 = "SPRITESHEET_PLAYER_1",
    SPRITESHEET_PLAYER_2 = "SPRITESHEET_PLAYER_2",
    SPRITESHEET_PROJECTILES = "SPRITESHEET_PROJECTILES",
    SOUND_BUTTON_CHANGE = "SOUND_BUTTON_CHANGE",
    SOUND_ENEMY_DESTROYED = "SOUND_ENEMY_DESTROYED",
    SOUND_GAME_OVER = "SOUND_GAME_OVER",
    SOUND_LEVEL_FINISHED = "SOUND_LEVEL_FINISHED",
    SOUND_MUSIC_GAME = "SOUND_MUSIC_GAME",
    SOUND_MUSIC_MENU = "SOUND_MUSIC_MENU",
    SOUND_PLAYER_HIT = "SOUND_PLAYER_HIT",
    SOUND_SHOT = "SOUND_SHOT",
}