export enum Tags
{
    ENEMY_CIRCLE = "ENEMY_CIRCLE",
    PLAYER_PROJECTILE = "PLAYER_PROJECTILE",
    PLAYER = "PLAYER"
}

export enum Messages
{
    ENEMY_DESTROYED = "ENEMY_DESTROYED",
    PLAYER_HIT = "PLAYER_HIT",
    PROJECTILE_SHOT = "PROJECTILE_SHOT",
    PROJECTILE_DESTROYED = "PROJECTILE_DESTROYED",
    PROJECTILE_COLLISION = "PROJECTILE_COLLISION",
    ENEMY_COLLISION = "ENEMY_COLLISION",
    GAME_START = "GAME_START",
    GAME_OVER = "GAME_OVER",
    GAME_WON = "GAME_WON",
    MAIN_MENU = "MAIN_MENU"
}

export enum Attributes
{
    CONTROLS = "CONTROLS",
    ENEMY_TYPE = "ENEMY_TYPE",
    ENEMY_SPEED = "ENEMY_SPEED",
    ENEMY_VELOCITY = "ENEMY_VELOCITY",
    PROJECTILES_AVAILABLE = "PROJECTILES_AVAILABLE",
    PROJECTILE_SHOOTER = "PROJECTILE_SHOOTER"  // the person that shot the projectile
}

export enum GlobalAttributes
{
    GAME_MODE = "GAME_MODE",  // singleplayer (1) or multiplayer (2)
    GAME_STATE = "GAME_STATE",
    ENEMIES_COUNT = "ENEMIES_COUNT",
    KEY_INPUT = "KEY_INPUT",
    PLAYERS_COUNT = "PLAYERS_COUNT",  // number of players currently alive
    PROJECTILES_MAX = "PROJECTILES_MAX",
}