export enum Tags
{
    ENEMY_CIRCLE = "ENEMY_CIRCLE",
    PLAYER_PROJECTILE = "PLAYER_PROJECTILE",
    PLAYER = "PLAYER"
}

export enum Messages
{
    PLAYER_HIT = "PLAYER_HIT",
    PROJECTILE_SHOT = "PROJECTILE_SHOT",
    PROJECTILE_DESTROYED = "PROJECTILE_DESTROYED"
}

export enum Attributes
{
    GAME_STATE = "GAME_STATE",
    KEY_INPUT = "KEY_INPUT",
    PROJECTILES_AVAILABLE = "PROJECTILES_AVAILABLE",
    PROJECTILES_MAX = "PROJECTILES_MAX",


}